### ISSUE TITLE
tsmarty2c.php - failing for (some) custom Smarty tags

### ISSUE THREAD

**Issue by deceze** [smarty-gettext/smarty-gettext#1]
When the Smarty opening/closing tags are set to `<!--{` and `}-->` (please don't ask), the tsmarty2c.php extraction utility fails to extract some content correctly, even with customised `$ldq` and `$rdq`. This is due to the use of negated character classes `[^{$ldq}]*`.

I don't think there's an elegant solution using regexen. I'd consider hijacking the Smarty parser to actually parse the template, though I don't know how feasible this is.

**Comment by glensc** [comment]
i'm working on new project, where such problems are more easier to solve because using smarty own parser:

https://github.com/smarty-gettext/tsmarty2c/issues/1

**Comment by glensc** [comment]
What version of Smarty is this?

I tried to set these separators with v3.1.31 and get error:

```
Syntax error in template "file:different-separator2.tpl"  on line 7 "<!--{Now with 20% discount!}-->" too many shorthand attributes
```
