### ISSUE TITLE
Broken merging of translated string

### ISSUE THREAD

**Issue by cuchac** [smarty-gettext/smarty-gettext#13]
[tsmarty2c.php:197](https://github.com/smarty-gettext/smarty-gettext/blob/88431fe1038b36b2f7fda625ac307a11b3eb21b7/tsmarty2c.php#L197) breaks message merging (updating existing po file when "-o" option is used), because output file is overwritten before any merging takes place and previous translations are lost.

Reproduce:
```
php tsmarty2c.php -o locale/sk.po templates
# translate some  strings in locale/sk.po
php tsmarty2c.php -o locale/sk.po templates
# Translated strings are gone
```

**Comment by glensc** [comment]
you're doing it wrong. tsmarty2c.php should be used only to extract strings and store to .pot
msgmerge should be done from pot -> po

see the example bottom of the readme:
https://github.com/smarty-gettext/smarty-gettext#tsmarty2cphp---the-command-line-utility
