### ISSUE TITLE
tsmarty2c.php do_file() pattern fails, when curly braces are used in a argument

### ISSUE THREAD

**Issue by wolf-w** [smarty-gettext/smarty-gettext#15]
The standard pattern `/\{\s*(t)\s*([^\}]*)\}+([^\{]*)\{\/\1\}/` does not match for
`{t foo={foo="foo"} bar={foo="bar"}}hello %1 %2{/t}` (see [here](https://regex101.com/r/PPO0SW/1)).
This is caused by `[^\}]*` (no curly brace between the opening `{t` and the closing `}`), it only allows that the last arguemnt of `{t}` is a plugin call (`\}+` as manny curly braces you want at the end), but not any other arguments (`{t foo=$foo bar={foo="bar"}}hello %1 %2{/t}` will match)

This could be fixed with this pattern: `/\{\s*(t)\s*(.*)\}+([^\}\}\{]*)\{\/\1\}/U` (see [here](https://regex101.com/r/PPO0SW/3)), which ends in the php pattern `"/{$ldq}\s*({$cmd})\s*(.*){$rdq}+([^{$rdq}{$ldq}]*){$ldq}\/\\1{$rdq}/U"`

**THIS IS ONLY TESTED IN MY CASE AND MAY NOT WORK IN EVERY CASE!**
I don't have the time to test this for all cases ;(

**Comment by glensc** [comment]
you sure those are valid in smarty?
fails here with v3.1.31

```
{t foo=$foo bar={foo="bar"}}hello %1 %2{/t}

PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "file:test1.html"  on line 1 "{t foo=$foo bar={foo="bar"}}hello %1 %2{/t}"  - Unexpected "=", expected one of: "}" <-- 
```

```
{t foo={foo="foo"} bar={foo="bar"}}hello %1 %2{/t}

PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "file:test2.html"  on line 1 "{t foo={foo="foo"} bar={foo="bar"}}hello %1 %2{/t}"  - Unexpected "=", expected one of: "}" <-- 
```

**Comment by glensc** [comment]
i'm working on new project, where such problems are more easier to solve because using smarty own parser:

https://github.com/smarty-gettext/tsmarty2c/issues/1

**Comment by glensc** [comment]
not valid Smarty input. no response from reporter. closing.

and the tool no longer supported in this repo.
use https://github.com/smarty-gettext/tsmarty2c instead.
