### ISSUE TITLE
tsmarty2c.php do_file() pattern fails, when delimiters are multi-char

### ISSUE THREAD

**Issue by petski** [smarty-gettext/smarty-gettext#20]
I use `[%` and `%]` as my delimiters.

I like to write my translations as following:
`[% t %]Now with 20% discount![% /t %]`

I changed the used regular expression to work around this issue:

`Before: "/{$ldq}\s*({$cmd})\s*([^{$rdq}]*){$rdq}+([^{$ldq}]*){$ldq}\/\\1{$rdq}/"`
`After : "/{$ldq}\s*({$cmd})\s*(.*?)\s*{$rdq}(.+?){$ldq}\s*\/\\1\s*{$rdq}/"`

(It actually resolves the multi-char delimiter, and it also adds support for an ending "ldq whitespace cmd whitespace rdq")

Patch: [tsmarty2c.php.patch.txt](https://github.com/smarty-gettext/smarty-gettext/files/1001310/tsmarty2c.php.patch.txt)

This issue is kinda related to https://github.com/smarty-gettext/smarty-gettext/issues/1 and https://github.com/smarty-gettext/smarty-gettext/issues/15

**Comment by glensc** [comment]
i'm working on new project, where such problems are more easier to solve because using smarty own parser:

https://github.com/smarty-gettext/tsmarty2c/issues/1

**Comment by glensc** [comment]
solved with https://github.com/smarty-gettext/tsmarty2c/pull/9
