### ISSUE TITLE
Translating default values

### ISSUE THREAD

**Issue by kordianbruck** [smarty-gettext/smarty-gettext#21]
I'm regularly using the `default` modifier. Is there any way to translate those default strings?

**Comment by glensc** [comment]
throw in an example!

**Comment by kordianbruck** [comment]
```
{$greeting|default:'Welcome'}
```
for example

**Comment by glensc** [comment]
use [capture](http://www.smarty.net/docs/en/language.function.capture.tpl) block, something like:

```smarty
{capture name="default_greeting"}
{t}Welcome{/t}
{/capture}
{$greeting|default:$default_greeting}
```

**Comment by kordianbruck** [comment]
I guess that works as well, but its kinda a lot of code.

Writing a custom modifier that will translate and mimic the `default` modifier would also be possible. I can create a PR for that.
How would we add those string to the parsing script tho? Is it even a good idea?

**Comment by glensc** [comment]
you could also use translations from php side:

```php
$smarty->assign('default_welcome', _('Welcome'));
```

to extend syntax, it should be either:
1. done by smarty (`{$greeting|default:{t}Welcome{/t}}`
2. being attribute of `{t}` tag.

i'm not touching parser from this project anymore,
efforts go to new project: https://github.com/smarty-gettext/tsmarty2c

**Comment by kordianbruck** [comment]
I don't see how one could mimic the behaviour by extend the `{t}` tag. That does not make sense.

The first option `{$greeting|default:{t}Welcome{/t}}` seems more logical to me. I'll try that.

Thanks

**Comment by glensc** [comment]
```
{t default="welcome"}welcome{/t}
```

is possible, it `block.t`. finds that TEXT has no value, uses `$default` parameter value translation.

but it's just an idea, did not think it through fully,

**Comment by kordianbruck** [comment]
That does something completely different though. My example checks if the variable is set, if not it will replace it. Yours checks if there is a translation for that term and replaces it with something different.
