### ISSUE TITLE
Smarty_Internal_Compile_T

### ISSUE THREAD

**Issue by sirio3mil** [smarty-gettext/smarty-gettext#22]
After installing this library with composer when smarty compile for first time each template I get this errors

> Warning: include_once(Smarty_Internal_Compile_T.php): failed to open stream: No such file or directory in file on line x
> 
> Warning: include_once(): Failed opening 'Smarty_Internal_Compile_T.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in file on line x
> 
> Warning: include_once(Smarty_Internal_Compile_Tclose.php): failed to open stream: No such file or directory in file on line x
> 
> Warning: include_once(): Failed opening 'Smarty_Internal_Compile_Tclose.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in file on line x

Those files even exist! When I reload warnings disappear but after some time when smarty have to recompile it shows again.

Smarty 3.1.31
Smarty Gettext 1.5.1
PHP 7.1.5

I have my own spl_autoload_register after composer autoload.

Regards

**Comment by glensc** [comment]
this can't be smarty-gettext fault.

however, try with php sapi that is non threaded. for example can you reproduce this with php-cli?
try disabling any opcode optimizes (opcache, zend-optimizer, apc)

also, if smarty version is upgraded, it's best to delete cache files, your error is not related to smarty update?
