### ISSUE TITLE
Question: what's the best way to handle variables ?

### ISSUE THREAD

**Issue by dfranco** [smarty-gettext/smarty-gettext#23]
Hi,

Quick question ...

I'm trying to figure out the best way to handle the case when you have in a Smarty template
`<h3>{t}{$page_name}{/t}</h3>`

and $page_name is set like this
`$view->assign('page_name', $page_name);`

Let's say, $page_name is defined in a conditional way like in the example below
`if( empty($mug) ) {`
` $page_name = 'We need more coffee';`
`}else {`
` $page_name = 'We have enough coffee;`
`}`

What's the best way to handle this with smarty-gettext ?

P.S: This is just an example, I always have enough coffee ;)

Thanks for your feedback

**Comment by glensc** [comment]
variant 1: use php side (and don't forget to run xgettext to extract keywords):

```php
if (empty($mug)) {
  $page_name = _('We need more coffee');
} else {
  $page_name = _('We have enough coffee');
}
```

variant 2: add condition in smarty:

```smarty
{if $mug}
<h3>{t}We need more coffee{/t}</h3>
{else}
<h3>{t}We have enough coffee{/t}</h3>
{/if}
```

variant 3: create extra file where you define such keywords, you don't have to use that file in your application, but used only to grab translation keywords. can use either smarty or php syntax.

**Comment by dfranco** [comment]
variant 1 seems to fit pretty well with my PHP project.

Thanks for your feedback
