### ISSUE TITLE
Wrong header format

### ISSUE THREAD

**Issue by Rudloff** [smarty-gettext/smarty-gettext#24]
Hello,

I'm using smarty-gettext 1.5.1.
It works pretty well but the files it generates always start like this:
```po
msgid ""
msgstr "Content-Type: text/plain; charset=UTF-8\n"
```

I had a look at the gettext doc and I think it should look like this instead:
```po
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\n"
```

**Comment by glensc** [comment]
while it may not be visually appealing to you, both are correct for gettext syntax. if you wish, you can reformat the output with tools like msgcat or msgmerge.

do you have any actual error with this? please do present it.

**Comment by Rudloff** [comment]
I had some trouble getting xgettext to add new strings to files generated by smarty-gettext and I thought it was because the header was malformed (also because Github's syntax highlighting does not like this format) but it turns out I was doing something wrong.
