### ISSUE TITLE
tsmarty2c how add folder?

### ISSUE THREAD

**Issue by thecombo** [smarty-gettext/smarty-gettext#31]
Hello
I have implemented smarty-gettext in my project and everything works fine.
But I would like to extract translations from other types of files.

Can you explain these examples to me better? or where do I add the directory that will be scanned?

example 1:
tsmarty2c -o smarty.pot ...
xgettext --add-comments=TRANSLATORS: --keyword=gettext --keyword=_  --output=code.pot ...
msgcat -o template.pot code.pot smarty.pot
rm -f code.pot smarty.pot

example 2:
find templates -name '*.tpl.html' -o -name '*.tpl.text' -o -name '*.tpl.js' -o -name '*.tpl.xml' | xargs tsmarty2c.php -o smarty.pot

**Comment by glensc** [comment]
first you may want to see if the new generation tool makes more sense:
- https://github.com/smarty-gettext/tsmarty2c

**Comment by glensc** [comment]
tsmarty2c is not supported here, use new project:
- https://github.com/smarty-gettext/tsmarty2c

**Comment by thecombo** [comment]
> tsmarty2c is not supported here, use new project:
> 
> * https://github.com/smarty-gettext/tsmarty2c

Thanks :+1:
