### ISSUE TITLE
tsmarty2c.php is deprecated but still present

### ISSUE THREAD

**Issue by shoulders** [smarty-gettext/smarty-gettext#35]
hi

you say that **tsmarty2c.php** is deprecated in this project but it is still present.

can you remove the files and instrucitons from the project so it is less confusing.

A link to the new project and instructions would be a useful replacement.

thanks

**Comment by glensc** [comment]
You are welcome to send PR with the change to documentation indicating it's deprecated.

also, tsmarty2c has some unresolved issues, so it's not 100% replacement

**Comment by shoulders** [comment]
I am not sure what the difference is between **tsmarty2c.php** and **tsmarty2c**.

I thought they were same but now as a separate project so i might struggle with this one.

**Comment by glensc** [comment]
see open issues in the project

**Comment by shoulders** [comment]
@glensc 

I will **PR** the other issues, but this is just confusing, so i will leave this one to you. 😃 

**P.S.** I really do appreciate **smarty-gettext** and I wrote some instructions somewhere to use your command line tool with PoEdit, Windows and xampp.

**Comment by glensc** [comment]
it is deprecated already: https://github.com/smarty-gettext/smarty-gettext/pull/32

**Comment by glensc** [comment]
Deprecation does not mean removed: https://en.wikipedia.org/wiki/Deprecation, deprecated by still present is pretty accurate outcome of deprecation.
