### ISSUE TITLE
composer does not automatically install the smarty files

### ISSUE THREAD

**Issue by shoulders** [smarty-gettext/smarty-gettext#36]
The composer install does not install the following in to their folders in smarty, but I am guessing this is expected.
- block.t.php
- function.locale.php

Could you add some notes about this (unless I am doing something wrong) that these files need to be manually moved to the `smarty/libs/plugins` folder

I am assuming the composer routine add the required dependencies so doing this should still be done?

Any clarification with this would be appreciated.

**Comment by shoulders** [comment]
I was incorrect with this, so this can be ignored.

I have modified `smarty-gettext` to use mo translate rather than native gettext

**Comment by glensc** [comment]
you can cross-link your changes here, if they are public
