### ISSUE TITLE
Plural form in Slavic languages...

### ISSUE THREAD

**Issue by JulianVolodia** [smarty-gettext/smarty-gettext#4]
What about ngettext()?

(thread on php.net)
http://php.net/manual/en/function.ngettext.php
<?php

setlocale(LC_ALL, 'cs_CZ');
printf(ngettext("%d window", "%d windows", 1), 1); // 1 okno
printf(ngettext("%d window", "%d windows", 2), 2); // 2 okna
printf(ngettext("%d window", "%d windows", 5), 5); // 5 oken

?>

**Comment by mattez** [comment]
@JulianVolodia when you close this issue it will be nice to also add some solution/answer for this. It would be a bit of a time saver.

**Comment by JulianVolodia** [comment]
@mattez wut? :)
When I should close it? If:
1) I have no power to do that - because @glensc already closed it (sic!)^234 ;)
2) I have no power to do that - I am nobody for that project ;)

BTW. that was years ago... Project has dependency on gettext in Smarty, but all msgs was written in Polish with *.po files to translate to another langs (by design, no way to change that...) and tried to do it using gettext features. Nowadays I don't participate in that project so I don't know how they fixed that problem. :)

IMHO best is to:
- write base msgs in code in EN and translate from EN as @glensc suggested (because of gettext design...),
- try (harder than hard...) to write msgs which not using that feature (sorry, but people from some Polish corporation told me that!)
but afaik they want to be cheaty cheetas and don't want do it that way...

Best regards @mattez and @glensc .

**Comment by mattez** [comment]
@JulianVolodia I`m really sorry. I completely overlooked that the issue was closed by @glensc. OMG. Sorry again. Have a nice days.
