### ISSUE TITLE
can you make 1.6.2 from the master so It contains the extra |8.0

### ISSUE THREAD

**Issue by timmit-nl** [smarty-gettext/smarty-gettext#40]
can you make 1.6.2 from the master so It contains the php 8.0 fix?

**Comment by timmit-nl** [comment]
I was mistaking. I only saw release 1.6.1....

**Comment by glensc** [comment]
published:
- https://github.com/smarty-gettext/smarty-gettext/releases/tag/1.6.2

it shows up now as latest
