### ISSUE TITLE
Smarty 4.x support

### ISSUE THREAD

**Issue by dfranco** [smarty-gettext/smarty-gettext#42]
Hello @glensc ,

Do you plan to support Smarty 4.x in  a future release ?

Thanks for your feedback

**Comment by dfranco** [comment]
Just a quick update for other users.

I managed to make smarty-gettext (@stable) working with Smarty 4.2.1.

If anyone is interested, I will add more details in this thread.

P.S: an update of this repo's README could be helpful too.

**Comment by glensc** [comment]
You should send pull request then

**Comment by PaintSplasher** [comment]
@dfranco Please give us more details, what changes are necessary. Thx.

**Comment by dfranco** [comment]
> @dfranco Please give us more details, what changes are necessary. Thx.

Hi @PaintSplasher,

Give me a couple of day and I'll create a PR.

**Comment by PaintSplasher** [comment]
Sounds great, happy new year :)

**Comment by dfranco** [comment]
> Sounds great, happy new year :)

Happy new year to you too 🎉

**Comment by dfranco** [comment]
> > Sounds great, happy new year :)
> 
> Happy new year to you too 🎉

Hi @PaintSplasher ,

Sorry for the late feedback, but I've been super busy over the last few days.

I won't be able to create a PR , too busy these days.

I'll add a comment here this evening or tomorrow to explain the "hack".

Best,

**Comment by PaintSplasher** [comment]
Hey, it's totally fine to just describe your changes.

**Comment by dfranco** [comment]
> Hey, it's totally fine to just describe your changes.

I agree, but it seem's that I've a small issue with translations using smarty-get text.

I'll fix it and put the necessary changes here

**Comment by dfranco** [comment]
Hello @PaintSplasher,

Here's a simplified version of how I've implemented it (testing French translations in this example)

composer.json
```
...
"require": {
...
  "smarty/smarty": "4.2.*",
  "smarty-gettext/smarty-gettext": "@stable",
...
```

Run
`composer update`

Make sure the locale fr_FR.utf8 is setup on your server

script-name.php
```
<?php

$language = 'fr_FR';
$charset = 'UTF-8';

putenv('LANGUAGE=' . $language . '.' . $charset);
putenv('LANG=' . $language . '.' . $charset);
setlocale(LC_ALL, $language . '.' . $charset);

bindtextdomain($this->domain, 'any/path/for/locale');
bind_textdomain_codeset('messages', $charset);
textdomain('messages');
```

setup gettext files structure like
```
any/
  path/
    for/
    locale/
      messages.po
      messages.mo
```

and then in your Smarty template, add this
```
...
<p>{t}Shopping cart{/t}
...
```

Not 100% sure you need to restart your web server (Apache, Nginx, etc.), bug you should see "Panier d'achat" on the web page if you've all setup correctly.

Hope it helps 😃

**Comment by glensc** [comment]
@dfranco doesn't look like you made any changes to smarty-gettext codebase.

also, you should never modify `composer.json`, manually, but rather use `composer install` or `composer require`

**Comment by dfranco** [comment]
> @dfranco doesn't look like you made any changes to smarty-gettext codebase.
> 
> 
> 
> also, you should never modify `composer.json` manually, but rather use `composer install` or `composer require`

I agree @glensc,
But my comment only to explain how to test, rather than explaining how to handle Composer dependencies

**Comment by glensc** [comment]
so, what, the composer.json needs to just allow smarty 4?

**Comment by dfranco** [comment]
> so, what, the composer.json needs to just allow smarty 4?

Yes

**Comment by dfranco** [comment]
and make sure that smarty-gettext doesn't use smarty_register_block function/method (only present in Smarty 3.x)

**Comment by glensc** [comment]
so why hasn't the pull request been created then if it's that easy?

**Comment by dfranco** [comment]
because I remember there was an issue while upgrade from Smarty 3 -> 4 while using latest version smarty-gettext.

I need to setup a "clean" dev env just to try to reproduce the issue I've faced.

A PR will come right after I've finished the setup of above environmenent.

Best,

**Comment by glensc** [comment]
I checked this project doesn't have smarty in composer dependencies, so only readme update to say Smarty 4 is supported.

**Comment by dfranco** [comment]
There it is https://github.com/smarty-gettext/smarty-gettext/pull/44 @glensc 

Thanks for your valuable feedbacks.
