### ISSUE TITLE
Parameter translation?

### ISSUE THREAD

**Issue by Whoknowsit** [smarty-gettext/smarty-gettext#5]
Based on your readme, i wonder how to translate the parameters?

    {t 1='one' 2='two' 3='three'}The 1st parameter is %1, the 2nd is %2 and the 3rd %3.{/t}

Or isn't that possible?

**Comment by glensc** [comment]
well, parameters are intended to use something variable, like number of apples in a basket, those aren't intended to be translated.

but you could use [capture](http://www.smarty.net/docs/en/language.function.capture.tpl) with another `{t}` block:
```
{capture assign="expand_all"}{t}Expand all collapsed cells{/t}{/capture}
{t 1=$expand_all}Teh %1{/t}
```
