### ISSUE TITLE
locale path template_dir

### ISSUE THREAD

**Issue by Olvikolvi** [smarty-gettext/smarty-gettext#8]
On Smarty template_dir can also be array.. Dont add this by default.

**Comment by glensc** [comment]
I suppose you are taking about [function.locale.php](https://github.com/smarty-gettext/smarty-gettext/blob/1.2.0/function.locale.php#L37)?

Can you make sample code how you use it?

PS: I still support Smarty2 with this plugin where it is `string`, not `array`.

**Comment by Olvikolvi** [comment]
Maby like this. Dont know why this path must be related to template_dir?:
-$path = $smarty->template_dir . $params['path'];
+$path = (is_array($smarty->template_dir)  ? $smarty->template_dir . $params['path']:$params['path']);

**Comment by glensc** [comment]
> Can you make sample code how you use it?

I mean please give me snippet yow you initialize your Smarty.

**Comment by Olvikolvi** [comment]
Check Notes here: http://www.smarty.net/docs/en/variable.template.dir.tpl
I use it like this. When use_include_path is true template_dir becomes as Array.
require_once("Smarty-3.1.16/libs/Smarty.class.php");
$smarty = new Smarty;
$smarty->use_include_path = true;
etc..

**Comment by glensc** [comment]
thanks. will try to reproduce this!

**Comment by chaos0815** [comment]
I've addressed the Smarty 3 issue in the commit mentioned above. 
Maybe you can have a look. I'm not sure about either backwards compatability nor the travis tests.

**Comment by glensc** [comment]
there's no answer to this question:
"I suppose you are taking about function.locale.php"?

maybe you can answer it?

**Comment by chaos0815** [comment]
sent a pull request with my changes.

**Comment by chaos0815** [comment]
So, I guess this issue is fixed then?

**Comment by glensc** [comment]
dunno about fix. haven't tested it yet. so therefore haven't tagged release either.

**Comment by chaos0815** [comment]
Well, the tests are fine and it works for me. All systems go.

**Comment by glensc** [comment]
[1.3.0](https://github.com/smarty-gettext/smarty-gettext/releases/tag/1.3.0) released!
