### ISSUE TITLE
tsmarty2c.php and plural format

### ISSUE THREAD

**Issue by Olvikolvi** [smarty-gettext/smarty-gettext#9]
If I use plural I got this errors.. How to deal with it?

test.po:19: message catalog has plural form translations...
test.po:2: ...but header entry lacks a "plural=EXPRESSION" attribute
test.po:19: message catalog has plural form translations...
test.po:2: ...but header entry lacks a "nplurals=INTEGER" attribute
test.po:2: warning: header field 'Project-Id-Version' missing in header
test.po:2: warning: header field 'PO-Revision-Date' missing in header
test.po:2: warning: header field 'Last-Translator' missing in header
test.po:2: warning: header field 'Language-Team' missing in header
test.po:2: warning: header field 'MIME-Version' missing in header
test.po:2: warning: header field 'Content-Transfer-Encoding' missing in header
test.po:2: warning: header field 'Language' missing in header

**Comment by glensc** [comment]
no idea what you are doing. not enough details.

**Comment by Olvikolvi** [comment]
I think it was msgfmt related problem. It just needs some additional parameters. I downloaded poedit and used it to create .mo files and it works just fine.
